static int in_char_array(char* haystack, char needle) {
	for(char* curr = haystack; *curr != '\0'; curr++) {
		if(*curr == needle) {
			return 1;
		}
	}

	return 0;
}

static char* invalid_2_letter_combos[26] = {
	"",	// a
	"qxz",	// b
	"jwx",	// c
	"x",	// d
	"",	// e
	"qvxz",	// f
	"vx",	// g
	"xz",	// h
	"",	// i
	"bcdghjlmnpqtvwxyz",	// j
	"qvxz",	// k
	"x",	// l
	"jxz",	// m
	"",	// n
	"",	// o
	"qvx",	// p
	"cdefghjklmnpqrstvwxyz",	// q
	"",	// r
	"x",	// s
	"qx",	// t
	"",	// u
	"bcfhjkmpq",	// v
	"jqvx",	// w
	"djkr",	// x
	"",	// y
	"fjx"	// z
};

int are_valid_2_letter_combos(char* str, int strlen) {
	for(int i = 0; i < strlen - 1; i++) {
		if(str[i] < 'a' || str[i] > 'z') {
			continue;
		}

		if(in_char_array(invalid_2_letter_combos[(int)str[i] - 'a'], str[i + 1])) {
			return 0;
		}
	}

	return 1;
}

static char* valid_3_letter_combos[26][26] = {
	{	// a
		"bcegiklmnrst",	// a
		"abdehijlnorsuwy",	// b
		"abcdehiklmnoqrstuy",	// c
		"abcdefghijklmnopqrstuvwyz",	// d
		"acdgjlmnorstuvz",	// e
		"aefgiklnorstuy",	// f
		"adefghilmnoprstuwy",	// g
		"adefhijlmnorstuwy",	// h
		"abcdefgijklmnpqrstuvwyz",	// i
		"aeiou",	// j
		"abcdefhiklnoprstuwy",	// k
		"abcdefghiklmnopqrstuvwyz",	// l
		"abcefhilmnoprstuwy",	// m
		"abcdefghijklmnopqstuvwxyz",	// n
		"bchiklmprstu",	// o
		"abdefhijklmnoprstuwy",	// p
		"iu",	// q
		"abcdefghijklmnopqrstuvwxyz",	// r
		"abcdeghiklmnopqrstuwy",	// s
		"abcefghiklmnoprstuvwyz",	// t
		"abdcefghijklmnpqrstvxz",	// u
		"adeilorsuvy",	// v
		"abdefghiklmnoprsty",	// w
		"aeilnoptuwy",	// x
		"abcdefghilmnoprstuwy",	// y
		"acdehilopqtuvyz"	// z
	}, {	// b
		"abcdefghiklmnoprstuvwxyz",	// a
		"aeilorsuy",	// b
		"aehlou",	// c
		"aeiou",	// d
		"abcdefghiklmnoqrstuvwxyz",	// e
		"eoru",	// f
		"or",	// g
		"aeou",	// h
		"abcdefgiklmnopqrstuvwz",	// i
		"eou",	// j
		"i",	// k
		"aeijouvy",	// l
		"aeiw",	// m
		"aeio",	// n
		"abcdefghijklmnoprstuvwxyz",	// o
		"lor",	// p
		"",	// q
		"aeinoruyz",	// r
		"acehikloptuy",	// s
		"aefilorsu",	// t
		"abcdefghijklmnopqrstxyz",	// u
		"ei",	// v
		"aeh",	// w
		"",	// x
		"abeghilnprstwz",	// y
		""	// z
	}, {	// c
		"bcdefghijklnmoprstuvwxy",	// a
		"er",	// b
		"aehiloruy",	// c
		"ao",	// d
		"abcdefghiklmnoprstuvwyz",	// e
		"a",	// f
		"eou",	// g
		"abcdefghilmnoprstuwy",	// h
		"abcdefglmnoprstuvz",	// i
		"",	// j
		"abcdefghijklmnoprstuwy",	// k
		"aeiouy",	// l
		"aei",	// m
		"aei",	// n
		"abcdefghiklmnopqrstuvwxyz",	// o
		"h",	// p
		"u",	// q
		"aeiouy",	// r
		"iot",	// s
		"aefilmnorsuy",	// t
		"abcdefilmnoprstuvz",	// u
		"e",	// v
		"",	// w
		"",	// x
		"abcdghilmnoprstx",	// y
		"ae"	// z
	}, {	// d
		"bcdefghiklmnoprstuvwyz",	// a
		"aeiloruy",	// b
		"ahloru",	// c
		"abehilnorsuy",	// d
		"abcdefghijklmnopqrstuvwxz",	// e
		"aeiloru",	// f
		"aeiklmorsuwy",	// g
		"aeiopu",	// h
		"abcdefgijklmnoprstuvwxz",	// i
		"aeiou",	// j
		"aei",	// k
		"aeiouy",	// l
		"aeiou",	// m
		"aeio",	// n
		"abcdefghilmnoprstuvwxyz",	// o
		"aehilor",	// p
		"u",	// q
		"aeiouy",	// r
		"acdefhiklmoptuwy",	// s
		"aehiors",	// t
		"abcdefghiklmnoprstvz",	// u
		"aeio",	// v
		"aeiory",	// w
		"",	// x
		"abefgiklmnsw",	// y
		"ehiu"	// z
	}, {	// e
		"bcdefghiklmnprstuvwz",	// a
		"abefilorstuy",	// b
		"acdehikloqrstuyz",	// c
		"abcdefghilmnoprstuwy",	// d
		"abcdfghijklmnprstuvwxyz",	// e
		"abcefilnorstuy",	// f
		"aefghilmnorsuwy",	// g
		"aeimnoruy",	// h
		"abcdefgijklmnprstuvz",	// i
		"aeiou",	// j
		"abdehiklnosy",	// k
		"abcdefghijklmnoprstuvwyz",	// l
		"abcefiklmnopstuy",	// m
		"abcdefhgijklmnopqrstuvwyz",	// n
		"cdefgiklmnprstuvwz",	// o
		"abcdefhiklmnoprstuwy",	// p
		"u",	// q
		"abcdefghijklmnopqrstuvwxyz",	// r
		"abcdeghiklmnopqstuwy",	// s
		"abcdefhiklmnoprstuwyz",	// t
		"bcdegiklmnprstvwx",	// u
		"aeilorstuvy",	// v
		"abcdefghilmnoprsty",	// w
		"acehilopqtuxy",	// x
		"abcdefhiklmnoprsw",	// y
		"abehioruvyz"	// z
	}, {	// f
		"bcdefghiklmnrstuvwxyz",	// a
		"aeou",	// b
		"a",	// c
		"or",	// d
		"abcdefgiklmnrstuvwyz",	// e
		"abehilmnorsuy",	// f
		"ah",	// g
		"aeo",	// h
		"abcdefgjlnorstvxz",	// i
		"o",	// j
		"a",	// k
		"aeiouy",	// l
		"a",	// m
		"eim",	// n
		"abcdegiklmnoprstuwxy",	// o
		"e",	// p
		"",	// q
		"aeiouy",	// r
		"aehikpt",	// s
		"abehilmnoswy",	// t
		"cdegjklmnrstz",	// u
		"",	// v
		"a",	// w
		"",	// x
		"i",	// y
		""	// z
	}, {	// g
		"abcdefghilmnoprstuvwyz",	// a
		"eioy",	// b
		"ah",	// c
		"aeoru",	// d
		"abcdefhilmnoprstuvwy",	// e
		"eiloru",	// f
		"abdehilnoprsy",	// g
		"abcdefghijlnoprstuwy",	// h
		"abcdefglmnoprstuvz",	// i
		"au",	// j
		"io",	// k
		"aeiouy",	// l
		"aeiosuy",	// m
		"abeilmopstu",	// n
		"abcdefgilmnoprstuvwy",	// o
		"aeilou",	// p
		"i",	// q
		"aeiouy",	// r
		"abhikopt",	// s
		"aehiorz",	// t
		"abcdefgijlmnoprstyz",	// u
		"",	// v
		"aehiory",	// w
		"",	// x
		"ablmnprwz",	// y
		"aeh"	// z
	}, {	// h
		"abcdefghiklmnoprstuvwyz",	// a
		"aeiloru",	// b
		"ahlor",	// c
		"aeioru",	// d
		"abcdefghiklmnopqrstuvwxyz",	// e
		"aou",	// f
		"aou",	// g
		"aeio",	// h
		"abcdefghjklmnopqrstuvz",	// i
		"ao",	// j
		"aehio",	// k
		"aeioruy",	// l
		"aeiosu",	// m
		"aehimnoqsuy",	// n
		"abcdefghiklmnoprstuvwy",	// o
		"ahilu",	// p
		"u",	// q
		"aeilmouy",	// r
		"acehikot",	// s
		"acefghijlmnorstuwyz",	// t
		"abcdefghiklmnprstvxy",	// u
		"ai",	// v
		"aehio",	// w
		"",	// x
		"abdegilmnprstux",	// y
		""	// z
	}, {	// i
		"bcdefghiklmnoprstuvwz",	// a
		"abceilmnorsuwy",	// b
		"acehiklmnorstuy",	// c
		"abdeghijlmnoprstuwy",	// d
		"bcdfghiklmnprstuvwyz",	// e
		"aefilorstuy",	// f
		"aefghilmnoprstuwyz",	// g
		"aeiou",	// h
		"ans",	// i
		"aikosu",	// j
		"adehiknosuy",	// k
		"abcdefghiklmnopqrstuvwy",	// l
		"abcefilmnoprstuwy",	// m
		"abcdefghijklmnopqrstuvwxyz",	// n
		"abcdefgiklmnprstuvwxz",	// o
		"abcefhiklmoprstuwyz",	// p
		"abiu",	// q
		"abcdefghiklmnoprstuvwyz",	// r
		"abcdefghijklmnopqrstuvyz",	// s
		"abcefhijlmnoprstuwyz",	// t
		"clmnorst",	// u
		"aeiouvy",	// v
		"aeio",	// w
		"aeiopty",	// x
		"au",	// y
		"aehimouvz"	// z
	}, {	// j
		"bcdeghiklmnprstuvwxyz",	// a
		"",	// b
		"",	// c
		"",	// d
		"acdefhjklnoprstvwz",	// e
		"k",	// f
		"",	// g
		"",	// h
		"abdfghklmntvw",	// i
		"",	// j
		"s",	// k
		"",	// l
		"",	// m
		"",	// n
		"abcdeghiklmnprstuvwy",	// o
		"",	// p
		"",	// q
		"a",	// r
		"s",	// s
		"",	// t
		"abdgijklmnprstvwx",	// u
		"",	// v
		"",	// w
		"",	// x
		"",	// y
		""	// z
	}, {	// k
		"abcdefghilmnoprstuwxyz",	// a
		"aeiloru",	// b
		"ahlu",	// c
		"aor",	// d
		"abcdefghiklmnoprstuvwy",	// e
		"aiou",	// f
		"aoru",	// g
		"aeimnorsuwyz",	// h
		"abcdefghiklmnoprstuvwy",	// i
		"ao",	// j
		"aeinou",	// k
		"aeiouy",	// l
		"aeo",	// m
		"aegiou",	// n
		"abcdefghjklmnoprstuvwy",	// o
		"aeilor",	// p
		"",	// q
		"aeiouy",	// r
		"abceghiklmoptuwy",	// s
		"aehioru",	// t
		"abdghiklmnoprstwyz",	// u
		"",	// v
		"aehioruy",	// w
		"",	// x
		"acdeijlorsuw",	// y
		""	// z
	}, {	// l
		"abcdefghijklmnopqrstuvwxyz",	// a
		"aeijlorsuvy",	// b
		"aehiklmoruy",	// c
		"abcefhilmnoprstuwy",	// d
		"abcdefghijklmnopqrstuvwxyz",	// e
		"abefghiloprstuw",	// f
		"aeioruy",	// g
		"aeio",	// h
		"abcdefghjklmnopqrstuvwxyz",	// i
		"aou",	// j
		"abehilmnoswy",	// k
		"abcdefghijmnoprstuvwy",	// l
		"aehilmnosuy",	// m
		"aeiosu",	// n
		"abcdefghiklmnopqrstuvwxyz",	// o
		"aefhilmorstuy",	// p
		"u",	// q
		"aeiouy",	// r
		"abcefhikmopstuwy",	// s
		"acdefhilmoprsuwyz",	// t
		"abcdefghijklmnoprstvxyz",	// u
		"adeioy",	// v
		"aeior",	// w
		"",	// x
		"abcdefghilmnoprstuwxz",	// y
		"aehn"	// z
	}, {	// m
		"abcdefghijklmnoprstuvwxyz",	// a
		"abdefiklmnorstuwy",	// b
		"abcdefghiklmnopqrv",	// c
		"iru",	// d
		"abcdefghijklmnoprstuvwxyz",	// e
		"eilouy",	// f
		"m",	// g
		"aeouz",	// h
		"abcdefgjklmnoprstuwxz",	// i
		"",	// j
		"i",	// k
		"aeioy",	// l
		"aeilouy",	// m
		"adeilosuy",	// n
		"abcdeghijklmnoprstuvwxyz",	// o
		"abdefghiklmnoprstuy",	// p
		"iu",	// q
		"aeiosy",	// r
		"abcdefhikmoptuy",	// s
		"ehr",	// t
		"abcdefghijklmnprstuz",	// u
		"ei",	// v
		"aeio",	// w
		"",	// x
		"aceiklnorst",	// y
		""	// z
	}, {	// n
		"abcdefghiklmnoprstuvwxyz",	// a
		"aeiloru",	// b
		"aehiklmorstuy",	// c
		"abcdefghijklmnopqrstuwy",	// d
		"abcdefghiklmnopqrstuvwxyz",	// e
		"aeiloru",	// f
		"abcdefhijklmnopqrstuwyz",	// g
		"aeinou",	// h
		"abcdefghijklmnopqrstuvwxz",	// i
		"aeiou",	// j
		"abcefghilmnorstuwy",	// k
		"aeiouy",	// l
		"aeiou",	// m
		"abehikmosuyz",	// n
		"abcdefghiklmnoprstuvwxyz",	// o
		"aehiloru",	// p
		"u",	// q
		"aeiouy",	// r
		"abcdefghiklmnopstuvwy",	// s
		"abcdefghilmnoprsuwyz",	// t
		"abcdefghijklmnoprstuxz",	// u
		"aeiouy",	// v
		"aehior",	// w
		"ei",	// x
		"abdehilmopqstvwx",	// y
		"aehiouwy"	// z
	}, {	// o
		"bcdfghklmnpqrstuvx",	// a
		"abcdefgijlnorstuvwy",	// b
		"acehikloqrstuy",	// c
		"abcdefghiklmnoprstuwyz",	// d
		"abcdfghiklmnoqrstuvwxy",	// e
		"aefilnorstuy",	// f
		"abcdefghijlmnorstuwy",	// g
		"aehilmnorsy",	// h
		"abcdefgklmnrstx",	// i
		"aeio",	// j
		"abcehiklmnorstuwy",	// k
		"abcdefghiklmnoprstuvwyz",	// l
		"abcdefilmnoprstuwy",	// m
		"abcdefghijklmnopqrstuvwxyz",	// n
		"bcdefghiklmnprstvz",	// o
		"acefghijklmoprstuwy",	// p
		"u",	// q
		"abcdefghiklmnopqrstuvwyz",	// r
		"abcefghiklmnopqstuvwyz",	// s
		"abcefghiklmnoprstuwy",	// t
		"abcdefghiklmnpqrstvxyz",	// u
		"aeginosuy",	// v
		"abcdefghiklmnoprstuwyz",	// w
		"abcefghinostuvwyz",	// x
		"abcdefhilmnorsu",	// y
		"aehilnouyz"	// z
	}, {	// p
		"abcdeghijklmnpqrstuvwxyz",	// a
		"aeloru",	// b
		"ahio",	// c
		"aior",	// d
		"abcdefgijklmnopqrstuvwxyz",	// e
		"aioru",	// f
		"aru",	// g
		"adeilnorstuy",	// h
		"acdefgiklmnopqrstuvxz",	// i
		"aeo",	// j
		"einw",	// k
		"aeiouy",	// l
		"aeou",	// m
		"eo",	// n
		"acdegiklmnoprstuvwxyz",	// o
		"aehilmorsuy",	// p
		"",	// q
		"aeiouy",	// r
		"abcefhikoqstuwy",	// s
		"acehilmnorsuwy",	// t
		"bcdefgklmnprstz",	// u
		"",	// v
		"aeior",	// w
		"",	// x
		"acghilmnorstwx",	// y
		"i"	// z
	}, {	// q
		"dlnt",	// a
		"a",	// b
		"",	// c
		"",	// d
		"",	// e
		"",	// f
		"",	// g
		"",	// h
		"hnqs",	// i
		"",	// j
		"",	// k
		"",	// l
		"",	// m
		"",	// n
		"m",	// o
		"",	// p
		"",	// q
		"",	// r
		"",	// s
		"",	// t
		"aehimouy",	// u
		"",	// v
		"",	// w
		"",	// x
		"",	// y
		""	// z
	}, {	// r
		"bcdefghijklmnopqrstuvwxyz",	// a
		"aeilorsuy",	// b
		"aehiklorstuy",	// c
		"abcefhilmnoprstuvwy",	// d
		"abcdefghijklmnopqrstuvwxyz",	// e
		"abdefilorsuy",	// f
		"aehilmnorsuy",	// g
		"aeiouy",	// h
		"abcdefghijklmnopqstuvwxyz",	// i
		"aeou",	// j
		"abdefhilmnoprstuwy",	// k
		"abdefhiopstuwy",	// l
		"abcefhilnoprstuwy",	// m
		"abcefhiklmnoprstuwy",	// n
		"abcdefghijklmnopqrstuvwxyz",	// o
		"aehilmnorstuy",	// p
		"u",	// q
		"aehiosuy",	// r
		"abcdefhiklmnopqrtuvwy",	// s
		"abcefghilmnorstuwyz",	// t
		"abcdefghijklmnoprstvwxyz",	// u
		"aeiouy",	// v
		"aehioru",	// w
		"ei",	// x
		"abcdegiklmnopstuw",	// y
		"aehikloty"	// z
	}, {	// s
		"abcdefghijklmnprstuvwxyz",	// a
		"aeioruy",	// b
		"aehilorsuy",	// c
		"aeioru",	// d
		"abcdefghijklmnopqrstuvwxy",	// e
		"aeiloruy",	// f
		"aeiortu",	// g
		"abcdefghiklmnoprstuvwy",	// h
		"abcdefghklmnopqrstuvxz",	// i
		"aou",	// j
		"aeijlmnorstuy",	// k
		"aeiouy",	// l
		"aeiosu",	// m
		"aeiouy",	// n
		"abcdefghijklmnoprstuvwxyz",	// o
		"abehilnorsuy",	// p
		"u",	// q
		"aeiosu",	// r
		"abcefhiklmnoprtuwy",	// s
		"abcdefghilmnoprsuwy",	// t
		"abcdefghiklmnoprstvwz",	// u
		"aei",	// v
		"aeiou",	// w
		"",	// x
		"bcdfgiklmnprstw",	// y
		"eity"	// z
	}, {	// t
		"abcdefghijklmnoprstuvwxy",	// a
		"aeiloru",	// b
		"aehiloruy",	// c
		"aio",	// d
		"abcdefghilmnopqrstuvwxyz",	// e
		"aeilou",	// f
		"aeoru",	// g
		"abcdefghiklmnopqrstuwy",	// h
		"abcdefghjklmnopqrstuvwz",	// i
		"a",	// j
		"ain",	// k
		"aeiouy",	// l
		"aeiou",	// m
		"aeiou",	// n
		"abcdefgijklmnopqrstuvwxyz",	// o
		"aehiloru",	// p
		"",	// q
		"aeiouy",	// r
		"abcdehiklmoptuvwy",	// s
		"aeghilmnorsuvwy",	// t
		"abcdefgilmnoprstvxyz",	// u
		"aio",	// v
		"aehior",	// w
		"",	// x
		"acdeghiklmnprstx",	// y
		"aegikmoprsy"	// z
	}, {	// u
		"abcdefghiklmnprstuvwy",	// a
		"abcdefghijlmnoprstuvwy",	// b
		"acehiklorstuy",	// c
		"abdeghilmnorsuwyz",	// d
		"abcdefghijlmnoprstuvyz",	// e
		"aefilmotu",	// f
		"abeghilmnosu",	// g
		"ainrs",	// h
		"abcdefgjklnoprstuvxyz",	// i
		"aioru",	// j
		"acehiklorstuy",	// k
		"abcdefgiklmnoprstuvwyz",	// l
		"abcdefilmnopqrstuvy",	// m
		"abcdefghijklmnopqrstuvwyz",	// n
		"dfikmnrstuy",	// o
		"abcdefghijklmoprstuwy",	// p
		"u",	// q
		"abcdefghiklmnopqrstuvyz",	// r
		"abcdehiklmnopqstuy",	// s
		"abcdefghilmnoprstuvwyz",	// t
		"lms",	// u
		"aeiorsu",	// v
		"aeo",	// w
		"eilotu",	// x
		"aeghilostuv",	// y
		"abcehimnouyz"	// z
	}, {	// v
		"abcdeghijklmnoprstuz",	// a
		"",	// b
		"",	// c
		"a",	// d
		"abcdefghiklmnprstwxyz",	// e
		"",	// f
		"o",	// g
		"",	// h
		"abcdefgjklmnoprstuvxz",	// i
		"",	// j
		"",	// k
		"ao",	// l
		"",	// m
		"i",	// n
		"cdegiklmnorstuvwy",	// o
		"",	// p
		"",	// q
		"aeio",	// r
		"k",	// s
		"u",	// t
		"elmnorst",	// u
		"eiy",	// v
		"",	// w
		"",	// x
		"isw",	// y
		""	// z
	}, {	// w
		"bcdfghiklmnprstuvwxyz",	// a
		"aeior",	// b
		"ao",	// c
		"aeilnorsuy",	// d
		"abdefghilnprstvyz",	// e
		"ailou",	// f
		"ailu",	// g
		"aeioy",	// h
		"cdefglmnprstvxyz",	// i
		"",	// j
		"einswy",	// k
		"aeiosy",	// l
		"aeio",	// m
		"abcefghiloprstuwy",	// n
		"bdefgklmnoprstuvwz",	// o
		"aehilou",	// p
		"",	// q
		"aeiouy",	// r
		"abcefhiklmoprstuwy",	// s
		"aehos",	// t
		"hlmnprs",	// u
		"",	// v
		"o",	// w
		"",	// x
		"acelno",	// y
		"iy"	// z
	}, {	// x
		"bcdglmnrstv",	// a
		"o",	// b
		"aehiloru",	// c
		"",	// d
		"cdgilmnrs",	// e
		"o",	// f
		"l",	// g
		"aiou",	// h
		"abcdefgilmnorstv",	// i
		"",	// j
		"",	// k
		"ey",	// l
		"a",	// m
		"ae",	// n
		"cdlmnprt",	// o
		"aeiloru",	// p
		"u",	// q
		"",	// r
		"w",	// s
		"abehiorsuy",	// t
		"abdlmrsz",	// u
		"i",	// v
		"eio",	// w
		"o",	// x
		"acegilms",	// y
		"e"	// z
	}, {	// y
		"bcdghklmnopqrstw",	// a
		"adeilorsuy",	// b
		"aehikloru",	// c
		"abeinor",	// d
		"abdefgiklmnoprstuvwy",	// e
		"aeiloru",	// f
		"aegilmnoru",	// g
		"enoy",	// h
		"deknps",	// i
		"a",	// j
		"eijo",	// k
		"aeiklopsuvy",	// l
		"abeimnopsuy",	// m
		"abcdegimnotxy",	// n
		"dfgklmnprstuvw",	// o
		"aehilnoprstu",	// p
		"u",	// q
		"adeginorstuy",	// r
		"abcefhilmopstuwy",	// s
		"aehiot",	// t
		"abcgiklmnprstz",	// u
		"aeo",	// v
		"aehior",	// w
		"ei",	// x
		"au",	// y
		"aeis"	// z
	}, {	// z
		"abcdghiklmnprstvz",	// a
		"eou",	// b
		"ao",	// c
		"a",	// d
		"abcdefgklmnprstuz",	// e
		"",	// f
		"e",	// g
		"einouy",	// h
		"abcegilmnoprst",	// i
		"",	// j
		"oy",	// k
		"eiy",	// l
		"aio",	// m
		"aei",	// n
		"adehilmnoprstuv",	// o
		"a",	// p
		"u",	// q
		"ao",	// r
		"cipt",	// s
		"elr",	// t
		"bceklmnrs",	// u
		"aeo",	// v
		"eio",	// w
		"",	// x
		"bgimru",	// y
		"abeilowy"	// z
	}
};

int are_valid_3_letter_combos(char* str, int strlen) {
	for(int i = 0; i < strlen - 2; i++) {
		if(str[i] < 'a' || str[i] > 'z') {
			continue;
		}

		int index = (int)str[i] - 'a';

		if(!in_char_array(valid_3_letter_combos[index][(int)str[i + 1] - 'a'], str[i + 2])) {
			return 0;
		}
		continue;
	}

	return 1;
}
